# netlify.toml

[build]
  publish = "site"
  command = "pip install -r requirements.txt && pip install . && python generate_graph_examples.py && mkdocs build"

  [build.environment]
    PYTHON_VERSION = "3.12"
